FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt .

RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY . .

EXPOSE 6821

RUN chmod +x entrypoint.sh

CMD ["entrypoint.sh"]
