version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "6821:6821"
    env_file:
      - ../../.env.prod
    command: gunicorn -w 2 --bind 0.0.0.0:6821 wsgi:app