prod_api_up: prod_api_build
	docker compose -f docker-compose.api-prod.yml up -d --build

prod_api_down:
	docker compose -f docker-compose.api-prod.yml down

prod_api_build:
	docker compose -f docker-compose.api-prod.yml build

