version: "3"

services:
  start_up_command:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ../.env.prod
    command: flask database init

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "6811:6811"
    env_file:
      - ../.env.prod
    volumes:
      - ./intents.json:/app/intents.json
    command: gunicorn -w 2 --bind 0.0.0.0:6811 wsgi:app
