FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY KMSUser/requirements.txt /app/KMSUser/
RUN pip install --no-cache-dir -r KMSUser/requirements.txt \
    && pip install "panel>=1.0.0" bokeh tiktoken  


COPY KMSUser /app/KMSUser
COPY common /app/common
COPY conf /app/conf
COPY assets /app/assets
COPY templates /app/templates


ENV PYTHONPATH=/app \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PANEL_PORT=6801 \
    BOKEH_ALLOW_WS_ORIGIN="*"

RUN useradd -m myuser \
    && chown -R myuser:myuser /app

USER myuser

EXPOSE 6801

CMD ["panel", "serve", "KMSUser/WebApp/kms_user.py", \
    "--address", "0.0.0.0", \
    "--port", "6801", \
    "--cookie-secret", "KMS!@#cookie123456secretUITServerPanel",\
    "--basic-auth", "conf/accounts.json", \
    "--basic-login-template", "templates/basic_login.html",\
    "--logout-template", "templates/logout.html",\
    "--index", "templates/index.html", \
    "--static-dirs", "assets=assets", \
    "--allow-websocket-origin", "*", \
    "--check-unused-sessions", "3600000"]